// Rate-refresh pipeline (middle path): applies the curated manifest at
// scripts/rates/rates.json, best-effort verifies it against provider pages,
// prints a price diff vs the previous snapshot, and writes the generated
// overlay consumed by src/data/models.js. No server, no DB, no auth.
//
//   npm run refresh            # verify online + regenerate
//   npm run refresh -- --offline   # skip network, just regenerate
//
// Manual overrides belong in rates.json (the manifest). The generated file is
// derived output — edit rates.json, not the generated file.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const manifestPath = join(root, 'scripts', 'rates', 'rates.json');
const generatedPath = join(root, 'src', 'data', 'rates.generated.js');

const offline = process.argv.includes('--offline');
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));

// ---- previous snapshot (for the diff) ----
let prev = null;
try {
  prev = await import(fileURLToPath(join(root, 'src', 'data', 'rates.generated.js')));
} catch {
  prev = null;
}
const prevOverlays = prev?.PRICE_OVERLAYS ?? null;

const diffField = (label, prevVal, newVal) => {
  if (prevVal === newVal) return null;
  const to = (n) => (n == null ? '—' : `$${n}`);
  return `  ${label}: ${to(prevVal)} → ${to(newVal)}`;
};

function printDiff(cur, prevOver, title) {
  console.log(`\n[rates] ${title}`);
  let changed = 0;
  for (const rec of cur) {
    const before = prevOver?.find((p) => p.id === rec.id);
    const keys = Object.keys(rec).filter((k) => k !== 'id');
    const lines = [];
    for (const k of keys) {
      const pv = before?.[k];
      const nv = rec[k];
      const fmt = (v) => (typeof v === 'object' && v ? JSON.stringify(v) : `${v}`);
      if (fmt(pv) !== fmt(nv) && !(pv === undefined)) {
        lines.push(`  ${k}: ${fmt(pv)} → ${fmt(nv)}`);
        changed += 1;
      }
    }
    if (lines.length) {
      console.log(` ${rec.id}`);
      for (const l of lines) console.log(l);
    }
  }
  if (!changed) console.log('  no price changes vs previous snapshot ✓');
}

// ---- best-effort live verification (auditor, not oracle) ----
async function verifySource(src) {
  try {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), 8000);
    const res = await fetch(src.url, {
      signal: ctrl.signal,
      headers: { 'user-agent': 'llm-token-calculator/1.0 rate-card verification' },
    });
    clearTimeout(timer);
    if (!res.ok) {
      return { ...src, verified: false, reason: `HTTP ${res.status}` };
    }
    const text = (await res.text()).toLowerCase();
    const checks = (src.checks ?? []).map((c) => ({
      pattern: c,
      matched: text.includes(c.toLowerCase()),
    }));
    const matched = checks.filter((c) => c.matched).length;
    return {
      ...src,
      verified: checks.length > 0 && matched === checks.length,
      matched,
      reason: `${matched}/${checks.length} markers matched`,
    };
  } catch (e) {
    return {
      ...src,
      verified: false,
      reason: e?.name === 'AbortError' ? 'timeout' : `unreachable (${e?.message ?? e})`,
    };
  }
}

let sources = [];
if (offline) {
  console.log('\n[rates] --offline: skipping network verification');
  sources = (manifest.sources ?? []).map((s) => ({ ...s, verified: false, reason: 'skipped (offline)' }));
} else {
  console.log('\n[rates] verifying against provider pages…');
  sources = await Promise.all((manifest.sources ?? []).map(verifySource));
  for (const s of sources) {
    console.log(`  ${s.name}: ${s.verified ? 'OK — all markers matched' : `PARTIAL/FAIL — ${s.reason}`}`);
  }
}

const asOf = new Date().toISOString().slice(0, 10);
const meta = {
  asOf,
  reviewed: manifest.reviewed,
  verified: sources.length > 0 && sources.every((s) => s.verified),
  verifiedSources: sources.filter((s) => s.verified).length,
  totalSources: sources.length,
  sources,
};

// ---- write generated overlay ----
const body = `// AUTO-GENERATED by scripts/refresh-rates.mjs — do not edit by hand.
// Run \`npm run refresh\` to re-verify against provider pages and re-apply the
// curated manifest in scripts/rates/rates.json.

export const PRICE_META = ${JSON.stringify(meta, null, 2)};

export const PRICE_OVERLAYS = {
  chat: ${JSON.stringify(manifest.chat, null, 2)},
  gen: ${JSON.stringify(manifest.gen, null, 2)},
};
`;
writeFileSync(generatedPath, body);
console.log(`\n[rates] wrote ${generatedPath.replace(root + '/', '')}`);
console.log(`[rates] snapshot as-of ${asOf} · verified ${meta.verified ? 'YES' : 'NO'} (${meta.verifiedSources}/${meta.totalSources} sources)`);

printDiff(manifest.chat, prevOverlays?.chat ?? [], 'chat models');
printDiff(manifest.gen, prevOverlays?.gen ?? [], 'image models');